---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading and preprocessing the data
```{r getdata}
# Unzip data file
unzip(data_file_name, exdir="./", overwrite=TRUE)
data <- read.csv("./activity.csv")
```


## What is mean total number of steps taken per day?
```{r meansteps}
# Load in dependencies
library(tidyr)
library(dplyr)
library(ggplot2)

# Group up number of steps by day and calculate total number of steps per day
data_totals <-
  data %>%
  group_by(date) %>%
  summarise(total_steps=sum(steps, na.rm=TRUE))

# Calculate mean and median of total steps per day
mean_steps <- mean(data_totals$total_steps, na.rm=TRUE)
median_steps <- median(data_totals$total_steps, na.rm=TRUE)

# Make histogram of step totals
with(data_totals,
     hist(data_totals$total_steps, breaks=30,
          xlab="Total Steps", main="Histogram of Total Steps Per Day"))

# Plot vertical lines at mean and median
abline(v=mean_steps, col="red", lty=2, lwd=2)
abline(v=median_steps, col="blue", lty=2, lwd=2)

# Add a legend for the Veritcal lines
legend("topright", legend=c("Mean", "Median"),
       col=c("red", "blue"), lty=2, lwd=2)
```
First we group the step numbers by the date using group_by and take the sum of the total steps on each day.

## What is the average daily activity pattern?
```{r dailyactivitypattern}
# Calculate average number of steps at each interval point across all days
activity_avgs <-
  data %>%
  group_by(interval) %>%
  summarise(mean_steps = mean(steps, na.rm=TRUE))

# Find interval point that has max number of average steps
max_steps <- max(activity_avgs$mean_steps)
max_interval <- activity_avgs$interval[activity_avgs$mean_steps == max_steps]
msg <- paste("Max:", as.character(floor(max_steps)), "steps")
# Plot average steps 
with(activity_avgs,
     plot(interval, mean_steps, type="n",
          xlab="Interval", ylab="Average Steps"))

title(main="Average Daily Activity")
lines(activity_avgs$interval, activity_avgs$mean_steps)
abline(v=max_interval, col="red", lty=2, lwd=2)
text(max_interval+330, max_steps-5, msg)
```


## Imputing missing values
```{r imputemissingvalues}
library(impute)
library(reshape2)
# Cast dataframe to wide format
wide <- dcast(data, interval~date, value.var="steps")

# Make rownames
rownames(wide) <- wide$interval
wide <- wide[,-1]

# Remove columns that don't have any values
is_all_na <- function(x){all(is.na(x))}
all_nas <- sapply(wide, is_all_na)
wide <- wide[!all_nas]

# Impute remaining data
data_matrix <- as.matrix(wide)
imputed <- impute.knn(data_matrix)$data


```


## Are there differences in activity patterns between weekdays and weekends?
```{r weekdayweedkenddiff}
library(lubridate)

# Create new column that shows if data is a weekday or weekend
weekend_or_weekday <- function(xday){
  weekdays <- c(2,3,4,5)
  lub <- wday(ymd(xday))
  ifelse(lub %in% weekdays, "weekday", "weekend")
}

# take mean steps of each interval on weekends and weekdays
weekday_means <- 
  data %>%
  mutate(weekday = weekend_or_weekday(date)) %>%
  group_by(weekday, interval) %>%
  summarise(mean_steps = mean(steps, na.rm=TRUE))

# Cast to wide format of dataset to make plotting easier
weekday_activity <- dcast(weekday_means, interval~weekday, value.var="mean_steps")

# Plot data
with(weekday_activity, plot(interval, weekday, type="n",
                            ylab="Average steps", xlab="Interval"))

title(main="Average Daily Activity on Weekdays vs Weekends")

lines(weekday_activity$interval, weekday_activity$weekday, col="red")
lines(weekday_activity$interval, weekday_activity$weekend, col="blue")

legend("topright", legend=c("Mean weekday steps", "Mean weekend steps"),
       col=c("red", "blue"), lty=2, lwd=2)
```

